version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: .env
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:6033"
  cache:
    image: redis
  server:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on: 
      - db